### PR TITLE
✨ 41 sparkles adding business hours component

### PR DESCRIPTION
**Pull request by langehm**
Issues #41

### CODE REVIEW

**Comment by langehm** [comment]
We should build a wrapper component for icons.

**Comment by langehm** [comment]
grafik
just a preview ...

**Comment by langehm** [comment]
The JS-Toggle does not work from the patternlab (missing the scripts). Currently, the toggle is done via a simple function. This can be reverted easily as soon as the scripts are imported into the project.

**Comment by FabianWilms** [comment]
> We should build a wrapper component for icons.

https://github.com/it-at-m/muc-patternlab-vue/issues/95

**Comment by FabianWilms** [comment]
> The JS-Toggle does not work from the patternlab (missing the scripts). Currently, the toggle is done via a simple function. This can be reverted easily as soon as the scripts are imported into the project.

I personally prefer having the js not in this library as long as we don't necessarily need it. It would bloat up the resulting web components and also would make the documentation more complex as to when you need to import the js-scripts, too and when you don't need them.

yes - currently there is no animation for the toggle-effect. but i think that's only a minor problem.

**Review by FabianWilms — APPROVED** [review]

**Pull request merged**
