### PR TITLE
60 integrate prettify check into cicd

### PR DESCRIPTION
**Pull request by langehm**
Issues #60

### CODE REVIEW

**Review by FabianWilms — DISMISSED** [review]
Nice!

**Comment by langehm** [comment]
Upon merging beta into this branch, some linting erros occured - therefore the new commit

**Comment by langehm** [comment]
Should we exclude the dist and storybook folder from eslint? The files inside are generated anyway and out of our controll

**Comment by FabianWilms** [comment]
> @FabianWilms Should we exclude the dist and storybook folder from eslint? The files inside are generated anyway and out of our controll

eslint can ignore the same files as in .gitignore - and `dist` and `storybook-static` are already in it. 

```
--ignore-path .gitignore
```

**Review by FabianWilms — APPROVED** [review]

**Pull request merged**
